DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(ID LONG AUTO_INCREMENT PRIMARY KEY, MATRICULA VARCHAR(60) NOT NULL, NOMBRE VARCHAR(60) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);
DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (ID LONG AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(50)
NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(50) NOT NULL, PROVINCIA VARCHAR(50) NOT NULL);
DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (ID LONG AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT
NULL, DNI INT NOT NULL, FECHA_INGRESO DATE NOT NULL, DOMICILIO_ID LONG);

DROP TABLE IF EXISTS TURNOS;
-- CREATE TABLE TURNOS (ID LONG AUTO_INCREMENT PRIMARY KEY, PACIENTE_ID LONG NOT NULL,--
CREATE TABLE TURNOS (ID LONG AUTO_INCREMENT PRIMARY KEY, PACIENTE_ID LONG,
ODONTOLOGO_ID LONG, FECHA_HORA DATE NOT NULL);
